### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by pselle** [JarvusInnovations/SeptaMobi#5]
Is this project dead? Getting these errors in the console, unable to load. The app.json goes to a weird login page.

Application Cache Error event: Manifest fetch failed (401) http://septa.mobi/app/SeptaMobi/cache.appcache septa.mobi/:1
Failed to load resource: the server responded with a status of 401 (Unauthorized) http://septa.mobi/app/SeptaMobi/build/production/app.json?1416359389270
Failed to load resource: net::ERR_CACHE_MISS

**Comment by themightychris** [comment]
@pselle thanks for the report, give it a try now

**Comment by pselle** [comment]
Yay! I noticed it was broke on mobile some weeks ago, only checked the browser yesterday. What was the fix? I see it wasn't in the code

**Comment by themightychris** [comment]
Well this repo is actually for the never-launched http://v3.septa.mobi/

But the fix was in the web server configuration, I screwed up a past update that had the app change to loading its html5 manifest from a path that was 401 protected. I never noticed because Chrome would just ignore the manifest when it couldn't load it, but Safari halts loading the page apparently.
